# Generated by Django 5.1.6 on 2025-05-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name="Organization's INN")),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(unique=True, verbose_name="Operation's ID")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('payer_inn', models.CharField(max_length=12, verbose_name="Taxpayer's INN")),
                ('document_number', models.CharField(max_length=50, verbose_name="Doc's number")),
                ('document_date', models.DateTimeField(verbose_name="Doc's date")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of record creation')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount of change')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='New balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of record change')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to='webhooks.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhooks.payment')),
            ],
            options={
                'verbose_name': 'Balance log',
                'verbose_name_plural': 'Balance logs',
            },
        ),
    ]
